### PR TITLE
simple API server added

### PR DESCRIPTION
**Pull request by sabitertan**
This can help a new starter to understand better about API calls.

### CODE REVIEW

**Comment by sabitertan** [comment]
It lives under data/ folder at top level, and you need to run it explicitly.

**Comment by marinav** [comment]
Hi,

Thank you @sabitertan for your exemple, I tryied it with an external api, I see data in my page but SSR is no more working...My currentUser in my preloaded state is empty and I don't understand why 😢 
Do you have the same behaviour ?

Thank you

**Comment by cereallarceny** [comment]
@sabitertan I'm afraid I can't accept this PR as you added over 16,000 lines of code to the project.  Please clean it up, or update it to the current `master` branch and I can reconsider.  Closing for now.

**Comment by sabitertan** [comment]
Sorry I used npm and did'nt realize package-lock.json carried over. I created cleaner PR.

**Pull request closed without merging**
